name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  authenticate:
    name: Authenticate
    runs-on: ubuntu-latest
    outputs:
      docker-auth: ${{ steps.docker-login.outputs.auth }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        id: docker-login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  build:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build and Push Docker Image
        run: |
          echo "${{ steps.docker-login.outputs.auth }}" | docker login --username ${{ vars.DOCKERHUB_USERNAME }} --password-stdin
          docker buildx build --platform linux/amd64 -t cyberprince/argocd-experiment:v1.0 --push ./backend-code
