name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Image Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t cyberprince/argocd-experiment:v1.0 --push ./backend-code

  authenticate:
    name: GCP Authenticate
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        name: Configure GCP Credentials
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'  # Store the service account JSON key in GitHub Secrets

      # Set up the gcloud CLI
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: 'flask-argocd-experiment'  # Replace with your GCP project ID
          install_components: 'kubectl'  # Optional: Install additional gcloud components like kubectl
          version: '>= 363.0.0'  # Ensures compatibility with Workload Identity Federation if needed

      # Use the gcloud CLI
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

