name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  authenticate:
    name: Authenticate to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Login to Docker Hub using authentication token
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

  build:
    name: Build and Push Docker Image
    needs: authenticate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t argocd-experiment:v1.0 --push .
