name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Image Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t cyberprince/argocd-experiment:v1.0 --push ./backend-code

  authenticate:
    name: GCP Authenticate
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        name: Configure GCP Credentials
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      # Set up the gcloud CLI
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2.1.1'
        with:
          project_id: 'flask-argocd-experiment'
          install_components: 'kubectl'  # Install kubectl for Kubernetes management
          version: '>= 363.0.0'  # Ensures compatibility with Workload Identity Federation

      # Enable required GCP services
      - name: Enable Kubernetes Engine API
        run: |
          gcloud services enable container.googleapis.com
          gcloud services enable compute.googleapis.com   

      # Creating GKE cluster with single zone and no autoscaling, autorepair, or autoupgrade
            # Creating GKE cluster with auto-upgrade enabled (since it's required for the Regular release channel)
      - name: 'GKS Cluster Creation'
        run: |
          gcloud container clusters create argocd-experiment-cluster \
          --zone europe-west3-a \
          --num-nodes 1 \
          --machine-type e2-micro \
          --enable-ip-alias \
          --release-channel regular \
          --no-enable-autorepair \
          --async


  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: authenticate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubernetes context
        run: |
          gcloud container clusters get-credentials argocd-experiment-cluster --zone europe-west3-a --project flask-argocd-experiment

      # Deploy the Docker image as a Kubernetes deployment
      - name: 'Create FlaskApp Deployment'
        run: |
          kubectl create deployment flaskapp --image=cyberprince/argocd-experiment:v1.0
          kubectl expose deployment flaskapp --type=LoadBalancer --port=5050 --target-port=5050

      # Optional: Update the Docker image version in GKE deployment (for subsequent updates)
      - name: 'Update Docker Image Version'
        run: |
          kubectl set image deployment/flaskapp flaskapp=cyberprince/argocd-experiment:v1.0
